In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn import tree
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score # to check the model accuracy
from sklearn.metrics import confusion_matrix # how many records are correctly classified and not classified correcty
from sklearn.naive_bayes import *

In [2]:
df=pd.read_csv("D:\\LetsUpgrade\\Day 24\\train.csv")

In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df.drop(['Cabin'],axis=1,inplace=True)

In [7]:
df.drop(['Name','Ticket'],axis=1,inplace=True)

In [8]:
label_encoder=preprocessing.LabelEncoder()

In [9]:
df['Sex']=label_encoder.fit_transform(df["Sex"])

In [10]:
df['Embarked']=label_encoder.fit_transform(df["Embarked"])

In [11]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

# Model 1

In [12]:
y=df['Pclass'] # Dependendent varibale

In [13]:
y

0      3
1      1
2      3
3      1
4      3
      ..
884    2
885    1
886    3
887    1
888    3
Name: Pclass, Length: 889, dtype: int64

In [14]:
X=df.drop(['Pclass','PassengerId'],axis=1) # Independent Variables

In [15]:
# randomly classified
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [16]:
clf=BernoulliNB()

In [17]:
ypred=clf.fit(X_train,y_train).predict(X_test)

In [18]:
accuracy_score(y_test,ypred,normalize=True)

0.5917602996254682

In [19]:
confusion_matrix(y_test,ypred)

array([[ 30,   8,  32],
       [  9,  10,  30],
       [ 24,   6, 118]], dtype=int64)

# Model 2

In [20]:
y1=df['Sex'] # Dependendent varibale

In [21]:
y1

0      1
1      0
2      0
3      0
4      1
      ..
884    1
885    0
886    0
887    1
888    1
Name: Sex, Length: 889, dtype: int32

In [22]:
X1=df.drop(['Sex','PassengerId'],axis=1) # Independent Variables

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X1,y1,test_size=0.3,random_state=0)

In [24]:
clf=BernoulliNB()

In [25]:
ypred=clf.fit(X_train,y_train).predict(X_test)

In [26]:
accuracy_score(y_test,ypred,normalize=True)

0.7453183520599251

In [27]:
confusion_matrix(y_test,ypred)

array([[ 49,  49],
       [ 19, 150]], dtype=int64)

# Model 3

In [28]:
y2=df['SibSp'] # Dependendent varibale

In [29]:
X2=df.drop(['SibSp','PassengerId'],axis=1) # Independent Variables

In [30]:
X_train,X_test,y_train,y_test=train_test_split(X2,y2,test_size=0.3,random_state=0)

In [31]:
ypred=clf.fit(X_train,y_train).predict(X_test)

In [32]:
accuracy_score(y_test,ypred,normalize=True)

0.6891385767790262

In [33]:
confusion_matrix(y_test,ypred)

array([[162,  20,   0,   0,   0,   0,   0],
       [ 43,  22,   0,   0,   0,   0,   0],
       [  6,   2,   0,   0,   0,   0,   0],
       [  5,   2,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0]], dtype=int64)

# Model 4

In [34]:
y3=df['Parch'] # Dependendent varibale

In [35]:
X3=df.drop(['Parch','PassengerId'],axis=1) # Independent Variables

In [36]:
X_train,X_test,y_train,y_test=train_test_split(X3,y3,test_size=0.3,random_state=0)

In [37]:
ypred=clf.fit(X_train,y_train).predict(X_test)

In [38]:
accuracy_score(y_test,ypred,normalize=True)

0.7153558052434457

In [39]:
confusion_matrix(y_test,ypred)

array([[182,  16,   0,   0,   0],
       [ 31,   9,   0,   0,   0],
       [ 24,   3,   0,   0,   0],
       [  1,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0]], dtype=int64)

# Model 5

In [40]:
y4=df['Embarked'] # Dependendent varibale

In [41]:
X4=df.drop(['Embarked','PassengerId'],axis=1) # Independent Variables

In [42]:
X_train,X_test,y_train,y_test=train_test_split(X4,y4,test_size=0.3,random_state=0)

In [43]:
ypred=clf.fit(X_train,y_train).predict(X_test)

In [44]:
accuracy_score(y_test,ypred,normalize=True)

0.7340823970037453

In [45]:
confusion_matrix(y_test,ypred)

array([[  0,   0,  49],
       [  0,   0,  22],
       [  0,   0, 196]], dtype=int64)